```{r}
#| output: false
#| echo: false

# Only edit below this line
#############################################################################
test_number <- 1

#Postition of Needle Valve O2 IGN
valve_O2_pos <- 0.5    #Turns from close

#Postition of Neelde valve PRDT
valve_prdt_pos <- 0.1  #Turns from close
#############################################################################
# Only edit above this line
```

---
title: "Pre-Detonator Unilateral Timing"
date: 12.10.2024 
author:
  - name: PERSEUS
    #orcid: 0009-0003-8702-2700
    email: nbartzsch@ethz.ch
    affiliation: 
      - name: ARIS
        url: https://aris-space.ch
editor: visual
format: 
  pdf:
    output-file: "results_test.pdf"
    documentclass: scrartcl
    geometry:
      - left=30mm
      - right=30mm
      - bottom=5mm
      - top=1mm
execute:
  eval: true
  echo: false
---

```{r}
#| output: false

##Load libraries

library(tidyverse)
library(gt)
```

```{r}
#| output: false
#| echo: false

# Only edit below this line
#############################################################################
# Import data
processed_data_sens <- read_csv(file = "processed_data/processed_data_sens.csv")
processed_data_act <- read_csv(file = "processed_data/processed_data_act.csv")

#############################################################################
# Only edit above this line

test_id <- test_number + 1
```

```{r}
#| output: false

table_geom <- data.frame(
  O2_pos = paste(valve_O2_pos, "[T.f.c]"),
  prdt_pos = paste(valve_prdt_pos, "[T.f.c]")
)

table_geom |> 
  gt() |> 
  cols_label(
    O2_pos = ("Position of Needle Valve O2 IGN"), 
    prdt_pos = ("Position of Needle Valve PRDT")
  ) |> 
  cols_align(align = "center")
```

```{r}

actuation_number_open <- (2*test_id)-1
actuation_number_close <- 2*test_id

actuation_time_open <- as.numeric(processed_data_act[actuation_number_open, 1])
actuation_time_close <-  as.numeric(processed_data_act[actuation_number_close, 1])

actuation_time_before <- actuation_time_open - 0.25
actuation_time_after <- actuation_time_open + 0.5 

plot_data <-  processed_data_sens |>
  filter(zero_time > actuation_time_before) |>
  filter(zero_time < actuation_time_after)

plot_data$zero_time <- plot_data$zero_time - actuation_time_open
plot_data$sensor_id <- as.factor(plot_data$sensor_id)
actuation_time_close_relative <-  actuation_time_close - actuation_time_open


#processed_data_prdt <- plot_data |>
#  filter(sensor_id == 105)

#processed_data_ign_ox <- plot_data |>
#  filter(sensor_id == 108)

#max_prdt_p <- max(processed_data_prdt$value)
#max_ign_ox_p <-  max(processed_data_ign_ox$value)

#table_max_p <-  data.frame(
#  prdt_p = paste(round(max_prdt_p, 2), "[barg]"),
#  ign_p = paste(round(max_ign_ox_p, 2), "[barg]")
#)

#table_max_p |> 
#  gt() |> 
#  cols_label(
#    prdt_p = ("Max Pressure in PRDT"), 
#    ign_p = ("Max Pressure in Ign Ox.")
#  ) |> 
#  cols_align(align = "center")


# 114 ign fuel pressure
# 115 prg pressure
# 121 prdt pressure 
```

### $H_2$ $Timing$

```{r, fig.width=11, fig.height=6}

new_labels <- c(
  "105" = "Pre-Detonator Pressure",
  "108" = "Ignition Ox Pressure"
)

#Plot the first response
plot_data_1 <- plot_data |>
  filter(sensor_id == 105)

plot_data_2 <- plot_data |>
  filter(sensor_id == 108)

#Ploting the data
ggplot(plot_data_1, aes(x = zero_time,
                      y = value,
                      color = sensor_id)) +
  geom_rect(aes(xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf),
            fill = "gray90", color = NA, alpha = 0.2) +
  geom_path(linewidth = 0.75)+
  labs(
    x = "Time [seconds]",
    y = "Pressure [barg]",
    color = "Pressure reading"
  ) +
  scale_color_manual(values = c("#001e5e"), labels = new_labels) +
  scale_x_continuous(
    breaks = seq(floor(min(plot_data$zero_time)), ceiling(max(plot_data$zero_time)), by = 0.1)
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5),
    panel.grid.minor.x = element_line(color = "gray90", linewidth = 0.2)
  )
```

### $O_2$ $Timing$

```{r, fig.width=11, fig.height=6}
ggplot(plot_data_2, aes(x = zero_time,
                      y = value,
                      color = sensor_id)) +
  geom_rect(aes(xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf),
            fill = "gray90", color = NA, alpha = 0.3) +
  geom_path(linewidth = 0.75)+
  labs(
    x = "Time [seconds]",
    y = "Pressure [barg]",
    color = "Pressure reading"
  ) +
  scale_color_manual(values = c("#ff0019"), labels = new_labels) +
  scale_x_continuous(
    breaks = seq(floor(min(plot_data$zero_time)), ceiling(max(plot_data$zero_time)), by = 0.1)
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(angle = 0, hjust = 1, vjust = 0.5),
    panel.grid.minor.x = element_line(color = "gray90", linewidth = 0.2)
  )
```
